name = "Isabel's Aeroscapes"
author = "nuclearobelisk"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aca80c88b8dd4764cc48b8bbb824a68f5429309cd9a5f19bc99d23767660b1d"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
