craftingTable.remove(<item:waystones:waystone>);
craftingTable.remove(<item:waystones:mossy_waystone>);
craftingTable.remove(<item:waystones:sandy_waystone>);
craftingTable.remove(<item:waystones:sharestone>);
craftingTable.remove(<item:waystones:white_sharestone>);
craftingTable.remove(<item:waystones:orange_sharestone>);
craftingTable.remove(<item:waystones:magenta_sharestone>);
craftingTable.remove(<item:waystones:light_blue_sharestone>);
craftingTable.remove(<item:waystones:yellow_sharestone>);
craftingTable.remove(<item:waystones:lime_sharestone>);
craftingTable.remove(<item:waystones:pink_sharestone>);
craftingTable.remove(<item:waystones:gray_sharestone>);
craftingTable.remove(<item:waystones:light_gray_sharestone>);
craftingTable.remove(<item:waystones:cyan_sharestone>);
craftingTable.remove(<item:waystones:purple_sharestone>);
craftingTable.remove(<item:waystones:blue_sharestone>);
craftingTable.remove(<item:waystones:brown_sharestone>);
craftingTable.remove(<item:waystones:green_sharestone>);
craftingTable.remove(<item:waystones:red_sharestone>);
craftingTable.remove(<item:waystones:black_sharestone>);
craftingTable.remove(<item:waystones:warp_plate>);
craftingTable.remove(<item:waystones:portstone>);
craftingTable.remove(<item:waystones:warp_stone>);
craftingTable.remove(<item:waystones:return_scroll>);
craftingTable.remove(<item:waystones:warp_dust>);
craftingTable.remove(<item:waystones:attuned_shard>);

craftingTable.removeByModid("vc_gliders");
smithing.removeByModid("vc_gliders");

craftingTable.addShaped("glider", <item:vc_gliders:paraglider_wood>, [[<item:minecraft:air>, <item:minecraft:stick>, <item:minecraft:air>],[<item:minecraft:stick>, <item:minecraft:paper>, <item:minecraft:stick>],[<item:minecraft:paper>, <item:minecraft:lead>, <item:minecraft:paper>]]);