# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				tropical_fish = true
				fox = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				villager = true
				wolf = true
				zombie_villager = true
				elder_guardian = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				robin = true
				boar = true
				dragonfly = true
				tortoise = true
				butterfly = true
				duck = true
				bear = true
				lizard = true
				zebra = true
				rattlesnake = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true

			[light_sources.settings.entities.uselessreptile]
				moleclaw = true
				wyvern = true

			[light_sources.settings.entities.mythicmounts]
				netherbat = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				cargo_airship = true
				gyrodyne = true
				biplane = true

			[light_sources.settings.entities.supplementaries]
				rope_arrow = true

